# Generated by Django 4.2.1 on 2023-05-28 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_coment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='coment',
            name='rate',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
