# Generated by Django 4.2.1 on 2023-06-03 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_coment_product_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
